import React from 'react';
import { 
  ResponsiveContainer, PieChart, Pie, Cell, LineChart, Line, XAxis, YAxis, CartesianGrid, 
  Tooltip, Legend, BarChart, Bar, AreaChart, Area 
} from 'recharts';
import { 
  Activity, ShieldCheck, ShieldAlert, Cpu, BarChart3, Clock, AlertTriangle, 
  TrendingUp, CalendarRange, CheckSquare
} from 'lucide-react';
import { 
  ANALYTICS_METRICS, SCAN_TREND_DATA, DAILY_SCAN_DATA, OCR_ACCURACY_DATA, PIE_STATUS_DATA 
} from './MockData';

export default function AnalyticsPage() {
  const metrics = [
    { label: 'Total Scanned', value: ANALYTICS_METRICS.totalScanned, sub: "All logs combined", icon: Activity, color: 'text-blue-500 bg-blue-500/10' },
    { label: 'Safe Medicines', value: ANALYTICS_METRICS.safeMedicines, sub: "Within valid lifespan", icon: ShieldCheck, color: 'text-green-500 bg-green-500/10' },
    { label: 'Expired Items', value: ANALYTICS_METRICS.expiredMedicines, sub: "Disposal recommended", icon: ShieldAlert, color: 'text-red-500 bg-red-500/10' },
    { label: 'OCR Avg Accuracy', value: ANALYTICS_METRICS.ocrAccuracy, sub: "EasyOCR token weight", icon: Cpu, color: 'text-purple-500 bg-purple-500/10' },
    { label: 'Detection Rate', value: ANALYTICS_METRICS.detectionAccuracy, sub: "YOLOv8 target match", icon: BarChart3, color: 'text-teal-500 bg-teal-500/10' },
    { label: 'AI Processing Time', value: ANALYTICS_METRICS.processingTime, sub: "End-to-end latency", icon: Clock, color: 'text-amber-500 bg-amber-500/10' }
  ];

  const summaryCards = [
    { title: "Today's Scans", val: "12 verified", desc: "+3 compared to yesterday", icon: TrendingUp },
    { title: "Weekly Reports", val: "68 verified", desc: "No critical failures", icon: CalendarRange },
    { title: "Monthly Reports", val: "184 verified", desc: "Average validation latency 1.24s", icon: CheckSquare }
  ];

  return (
    <div className="flex-1 max-w-6xl mx-auto px-4 py-8 space-y-8 text-left">
      
      {/* Header Info */}
      <div className="border-b pb-4">
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">
          AI System Analytics
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400">
          Advanced metrics, accuracy tracking, and scanning trends generated by VisionAid AI verification nodes.
        </p>
      </div>

      {/* Grid of 6 Key Metric Cards */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
        {metrics.map((m) => (
          <div key={m.label} className="glass-panel border rounded-2xl p-4 flex flex-col justify-between hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start gap-2">
              <span className="text-[11px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider leading-snug">
                {m.label}
              </span>
              <div className={`p-1.5 rounded-lg shrink-0 ${m.color}`}>
                <m.icon className="w-4 h-4" />
              </div>
            </div>
            <div className="mt-3">
              <p className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white tracking-tight">{m.value}</p>
              <p className="text-[9px] text-slate-400 dark:text-slate-500 font-light mt-0.5">{m.sub}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Grid of Interactive Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Pie Chart - Valid vs Expired */}
        <div className="glass-panel border rounded-3xl p-6 space-y-4">
          <h3 className="text-sm font-bold text-slate-700 dark:text-slate-350 uppercase tracking-widest">
            Valid vs Expired Medication Status
          </h3>
          <div className="h-64 relative flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={PIE_STATUS_DATA}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={85}
                  paddingAngle={4}
                  dataKey="value"
                >
                  {PIE_STATUS_DATA.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip 
                  contentStyle={{ 
                    background: 'rgba(15, 23, 42, 0.95)', 
                    borderRadius: '12px', 
                    border: '1px solid rgba(255,255,255,0.1)',
                    color: '#fff',
                    fontSize: '11px'
                  }} 
                />
                <Legend iconSize={8} layout="horizontal" verticalAlign="bottom" align="center" wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Line Chart - Daily Scans */}
        <div className="glass-panel border rounded-3xl p-6 space-y-4">
          <h3 className="text-sm font-bold text-slate-700 dark:text-slate-350 uppercase tracking-widest">
            Daily Scan Verification Volume
          </h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={DAILY_SCAN_DATA} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" className="dark:hidden" />
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" className="hidden dark:block" />
                <XAxis dataKey="day" stroke="#94a3b8" fontSize={11} tickLine={false} />
                <YAxis stroke="#94a3b8" fontSize={11} tickLine={false} />
                <Tooltip
                  contentStyle={{ 
                    background: 'rgba(15, 23, 42, 0.95)', 
                    borderRadius: '12px', 
                    border: '1px solid rgba(255,255,255,0.1)',
                    color: '#fff',
                    fontSize: '11px'
                  }} 
                />
                <Line type="monotone" dataKey="scans" stroke="#2563EB" strokeWidth={3} activeDot={{ r: 6 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Bar Chart - OCR Accuracy */}
        <div className="glass-panel border rounded-3xl p-6 space-y-4">
          <h3 className="text-sm font-bold text-slate-700 dark:text-slate-350 uppercase tracking-widest">
            AI Node Parsing Accuracy (%)
          </h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={OCR_ACCURACY_DATA} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" className="dark:hidden" />
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" className="hidden dark:block" />
                <XAxis dataKey="name" stroke="#94a3b8" fontSize={10} tickLine={false} />
                <YAxis domain={[80, 100]} stroke="#94a3b8" fontSize={11} tickLine={false} />
                <Tooltip
                  contentStyle={{ 
                    background: 'rgba(15, 23, 42, 0.95)', 
                    borderRadius: '12px', 
                    border: '1px solid rgba(255,255,255,0.1)',
                    color: '#fff',
                    fontSize: '11px'
                  }} 
                />
                <Bar dataKey="accuracy" fill="#14B8A6" radius={[6, 6, 0, 0]} barSize={32}>
                  {OCR_ACCURACY_DATA.map((entry, idx) => (
                    <Cell key={idx} fill={idx === 3 ? '#22C55E' : '#14B8A6'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Trend Area Chart - Monthly Scan Activity */}
        <div className="glass-panel border rounded-3xl p-6 space-y-4">
          <h3 className="text-sm font-bold text-slate-700 dark:text-slate-350 uppercase tracking-widest">
            Monthly Verification Trend
          </h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={SCAN_TREND_DATA} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorValid" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#22C55E" stopOpacity={0.2}/>
                    <stop offset="95%" stopColor="#22C55E" stopOpacity={0}/>
                  </linearGradient>
                  <linearGradient id="colorExpired" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#EF4444" stopOpacity={0.2}/>
                    <stop offset="95%" stopColor="#EF4444" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" className="dark:hidden" />
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" className="hidden dark:block" />
                <XAxis dataKey="month" stroke="#94a3b8" fontSize={11} tickLine={false} />
                <YAxis stroke="#94a3b8" fontSize={11} tickLine={false} />
                <Tooltip
                  contentStyle={{ 
                    background: 'rgba(15, 23, 42, 0.95)', 
                    borderRadius: '12px', 
                    border: '1px solid rgba(255,255,255,0.1)',
                    color: '#fff',
                    fontSize: '11px'
                  }} 
                />
                <Legend iconSize={8} layout="horizontal" verticalAlign="top" align="right" wrapperStyle={{ fontSize: '11px', paddingBottom: '10px' }} />
                <Area type="monotone" dataKey="valid" name="Valid" stroke="#22C55E" strokeWidth={2} fillOpacity={1} fill="url(#colorValid)" />
                <Area type="monotone" dataKey="expired" name="Expired" stroke="#EF4444" strokeWidth={2} fillOpacity={1} fill="url(#colorExpired)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

      </div>

      {/* Summary Reports Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {summaryCards.map((card) => (
          <div key={card.title} className="p-5 rounded-2xl border bg-white/60 dark:bg-slate-950/20 border-slate-200 dark:border-slate-800 flex items-start gap-4 shadow-sm hover:shadow-md transition-shadow">
            <div className="p-3 bg-blue-500/5 dark:bg-blue-500/10 text-blue-600 dark:text-teal-400 rounded-xl shrink-0">
              <card.icon className="w-5 h-5" />
            </div>
            <div className="space-y-1">
              <h4 className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">{card.title}</h4>
              <p className="text-base font-bold text-slate-800 dark:text-slate-200">{card.val}</p>
              <p className="text-[10px] text-slate-400 dark:text-slate-500 leading-snug">{card.desc}</p>
            </div>
          </div>
        ))}
      </div>

    </div>
  );
}
